version: "3.8"

services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    networks:
      - app-net
    ports:
      - "80:3000"

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://user:password@database:5432/songguesser?schema=public
    depends_on:
      - database
    networks:
      - app-net
    ports:
      - "4000:4000"
    command: sh -c "npx prisma migrate reset --force && npx prisma migrate generate && npx prisma migrate deploy && npm run import-words && npm run start:prod"

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: songguesser
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net
    ports:
      - "5435:5432"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-net
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - app-net
    depends_on:
      - prometheus
    command: >
      /bin/sh -c "until curl -s http://prometheus:9090/api/v1/status/buildinfo; do echo 'Waiting for Prometheus...'; sleep 2; done; /run.sh"

volumes:
  postgres_data:

networks:
  app-net:
